version: '3'

services:    
  apache:
    build:
      context: ./
    container_name: php-xdebug-container
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./:/var/www/html
    ports:
      - "3000:80"